/**
 * APP-6(D) / MIL-STD-2525D number-based symbol identification code (SIDC)
 * reference data, checked against MIL-STD-2525E Change 1 (`docs/MIL-STD-2525E.pdf`).
 *
 * Codes are 20-digit version 10 codes: positions 1–20 have the same structure
 * in 2525E, which adds positions 21–30 (common-modifier identifiers, frame
 * shape, country; appendix A, figure A-1). The land unit entity and modifier
 * lists are the ones milsymbol draws for symbol set 10 with `standard:
 * 'APP6'`; the 2525E(1) additions milsymbol cannot draw yet are left out.
 *
 * `in2525E` on an entity or modifier: absent = still in 2525E(1)'s land unit
 * tables (A-XXIII to A-XXV); `'common'` = 2525E moved it to the common
 * modifier tables (A-IX, A-X), coded there with the position 21/22 flag;
 * `'removed'` = no longer in 2525E. All three remain valid version 10 codes.
 */

/** Tag an entry with where 2525E(1) keeps it (see the module comment). */
function editionNote(in2525E) {
  return in2525E ? { in2525E } : {};
}

/** The ten fields of a 20-digit SIDC, in order, with their digit spans. */
export const SIDC_FIELDS = [
  {
    key: 'version',
    ref: 'A.5.3.1',
    label: 'Version',
    start: 0,
    length: 2,
    doc: 'Which edition of the harmonised standards (APP-6 and MIL-STD-2525) the code is written against; it goes up by one with each promulgated edition. 10 is APP-6(D)(1) / MIL-STD-2525D.',
  },
  {
    key: 'context',
    ref: 'A.5.3.2',
    label: 'Context',
    start: 2,
    length: 1,
    doc: 'First digit of the standard identity: whether the object is real, part of an exercise, or simulated. Exercise and simulation frames carry an X or S. 2525E adds restricted-target and no-strike contexts (3–8).',
  },
  {
    key: 'identity',
    ref: 'A.5.3.2',
    label: 'Standard identity',
    start: 3,
    length: 1,
    doc: 'Second digit of the standard identity: the threat posed by the object. The seven identities fall into four groups (unknown, friend, neutral, hostile), and the group sets the frame shape and fill colour.',
  },
  {
    key: 'symbolSet',
    ref: 'A.5.3.3',
    label: 'Symbol set',
    start: 4,
    length: 2,
    doc: 'The operating domain and kind of object (air, land unit, land equipment, sea surface…). It sets the frame shape and which entity table the icon code is read from.',
  },
  {
    key: 'status',
    ref: 'A.5.3.4',
    label: 'Status',
    start: 6,
    length: 1,
    doc: 'Present (solid frame) or planned/anticipated (dashed frame), and for present objects an optional operational condition bar below the frame.',
  },
  {
    key: 'hqtfd',
    ref: 'A.5.3.5',
    label: 'HQ / TF / dummy',
    start: 7,
    length: 1,
    doc: 'Headquarters staff (a line down from the frame’s lower left), task force bracket over the echelon, and feint/dummy chevron above the frame, alone or combined.',
  },
  {
    key: 'amplifier',
    ref: 'A.5.3.6',
    label: 'Echelon / mobility',
    start: 8,
    length: 2,
    doc: 'The amplifying descriptor. For units, the echelon marker above the frame (1x: brigade and below, 2x: division and above). For equipment, a mobility indicator below the frame (3x land, 4x snow, 5x water, 6x towed array).',
  },
  {
    key: 'entity',
    ref: 'A.5.4',
    label: 'Entity · type · subtype',
    start: 10,
    length: 6,
    doc: 'The main icon, read from the symbol set’s entity table: two digits of entity (the branch), two of entity type, two of subtype.',
  },
  {
    key: 'modifier1',
    ref: 'A.5.4',
    label: 'Sector 1 modifier',
    start: 16,
    length: 2,
    doc: 'A capability or support level drawn in the upper part of the frame (e.g. multiple rocket launcher, NATO medical role). If the entity is unspecified, both modifiers must be 00.',
  },
  {
    key: 'modifier2',
    ref: 'A.5.4',
    label: 'Sector 2 modifier',
    start: 18,
    length: 2,
    doc: 'A mobility or capability qualifier drawn in the lower part of the frame (e.g. airborne, mountain, heavy, towed).',
  },
];

/** MIL-STD-2525E table A-I. 12 (APP-6(D)(2)) was withdrawn. */
export const VERSIONS = [
  { code: '10', name: 'APP-6(D)(1) / MIL-STD-2525D', released: '2014 / 2017' },
  { code: '11', name: 'MIL-STD-2525D(1)', released: '2018' },
  { code: '13', name: 'MIL-STD-2525E', released: '2022' },
  { code: '14', name: 'APP-6(E)(1)', released: '2023' },
  { code: '15', name: 'MIL-STD-2525E(1)', released: '2025' },
  { code: '16', name: 'APP-6(E)(2)', released: '2025' },
];

export const CONTEXTS = [
  { code: '0', name: 'Reality' },
  { code: '1', name: 'Exercise' },
  { code: '2', name: 'Simulation' },
];

export const IDENTITIES = [
  {
    code: '0',
    name: 'Pending',
    doc: 'Detected but not yet evaluated. Yellow quatrefoil, dashed.',
  },
  {
    code: '1',
    name: 'Unknown',
    doc: 'Evaluated, but the identity cannot be determined. Yellow quatrefoil.',
  },
  {
    code: '2',
    name: 'Assumed friend',
    doc: 'Likely friendly on the available evidence. Blue rectangle, dashed.',
  },
  { code: '3', name: 'Friend', doc: 'An allied or own force. Blue rectangle.' },
  {
    code: '4',
    name: 'Neutral',
    doc: 'Neither supporting nor opposing friendly forces. Green square.',
  },
  {
    code: '5',
    name: 'Suspect / joker',
    doc: 'Likely hostile. Red diamond, dashed. In exercise context: joker, a friend acting as hostile (blue rectangle, J).',
  },
  {
    code: '6',
    name: 'Hostile / faker',
    doc: 'A threat. Red diamond. In exercise context: faker, a friend playing a hostile (blue rectangle, K).',
  },
];

/** Symbol sets drawn in the frame matrix; `unit` marks sets whose amplifier is an echelon. */
export const SYMBOL_SETS = [
  { code: '01', name: 'Air' },
  { code: '02', name: 'Air missile' },
  { code: '05', name: 'Space' },
  { code: '06', name: 'Space missile' },
  { code: '10', name: 'Land unit', unit: true },
  { code: '11', name: 'Land civilian unit/organization', unit: true },
  { code: '15', name: 'Land equipment' },
  { code: '20', name: 'Land installation' },
  { code: '25', name: 'Control measure' },
  { code: '30', name: 'Sea surface' },
  { code: '35', name: 'Sea subsurface' },
  { code: '36', name: 'Mine warfare' },
  { code: '40', name: 'Activity / event', unit: true },
  { code: '50', name: 'SIGINT – space' },
  { code: '51', name: 'SIGINT – air' },
  { code: '52', name: 'SIGINT – land' },
  { code: '53', name: 'SIGINT – surface' },
  { code: '54', name: 'SIGINT – subsurface' },
  { code: '60', name: 'Cyberspace' },
];

/** Frames shown side by side in the frame-shape reference. */
export const FRAME_SETS = ['01', '05', '10', '15', '20', '30', '35', '40', '60'];

export const STATUSES = [
  { code: '0', name: 'Present', doc: 'Solid frame.' },
  {
    code: '1',
    name: 'Planned / anticipated',
    doc: 'Dashed frame: intended, expected or suspected.',
  },
  { code: '2', name: 'Present – fully capable', doc: 'Green bar: 85 % or more capable.' },
  { code: '3', name: 'Present – damaged', doc: 'Yellow bar: degraded capability.' },
  { code: '4', name: 'Present – destroyed', doc: 'Red bar: combat ineffective.' },
  { code: '5', name: 'Present – full to capacity', doc: 'Blue bar: a facility at capacity.' },
];

export const HQTFD = [
  { code: '0', name: 'None', hq: false, tf: false, dummy: false },
  { code: '1', name: 'Feint / dummy', hq: false, tf: false, dummy: true },
  { code: '2', name: 'Headquarters', hq: true, tf: false, dummy: false },
  { code: '3', name: 'Feint / dummy HQ', hq: true, tf: false, dummy: true },
  { code: '4', name: 'Task force', hq: false, tf: true, dummy: false },
  { code: '5', name: 'Feint / dummy task force', hq: false, tf: true, dummy: true },
  { code: '6', name: 'Task force HQ', hq: true, tf: true, dummy: false },
  { code: '7', name: 'Feint / dummy task force HQ', hq: true, tf: true, dummy: true },
];

/** Echelons, smallest first. `rank` orders them for sanity checks and sorting. */
export const ECHELONS = [
  { code: '00', name: 'Unspecified', marker: '', rank: 0 },
  { code: '11', name: 'Team / crew', marker: 'Ø', rank: 1 },
  { code: '12', name: 'Squad', marker: '●', rank: 2 },
  { code: '13', name: 'Section', marker: '●●', rank: 3 },
  { code: '14', name: 'Platoon / detachment', marker: '●●●', rank: 4 },
  { code: '15', name: 'Company / battery / troop', marker: 'I', rank: 5 },
  { code: '16', name: 'Battalion / squadron', marker: 'II', rank: 6 },
  { code: '17', name: 'Regiment / group', marker: 'III', rank: 7 },
  { code: '18', name: 'Brigade', marker: 'X', rank: 8 },
  { code: '21', name: 'Division', marker: 'XX', rank: 9 },
  { code: '22', name: 'Corps / MEF', marker: 'XXX', rank: 10 },
  { code: '23', name: 'Army', marker: 'XXXX', rank: 11 },
  { code: '24', name: 'Army group / front', marker: 'XXXXX', rank: 12 },
  { code: '25', name: 'Region / theatre', marker: 'XXXXXX', rank: 13 },
  { code: '26', name: 'Command', marker: '++', rank: 14 },
];

/** Land unit entity branches (first two digits of the entity code). */
export const ENTITY_GROUPS = [
  {
    code: '11',
    name: 'Command and control',
    doc: 'Signal, liaison, civil-military cooperation, information and psychological operations.',
  },
  {
    code: '12',
    name: 'Movement and manoeuvre',
    doc: 'Combat arms that close with the enemy: infantry, armour, reconnaissance, aviation, special forces.',
  },
  {
    code: '13',
    name: 'Fires',
    doc: 'Field artillery, mortars, air defence, missiles and the targeting that supports them.',
  },
  {
    code: '14',
    name: 'Protection',
    doc: 'Engineers, CBRN defence, military police, EOD, security and force protection.',
  },
  {
    code: '15',
    name: 'Intelligence',
    doc: 'Military intelligence, electronic warfare, counter-intelligence, interrogation and sensors.',
  },
  {
    code: '16',
    name: 'Sustainment',
    doc: 'Logistics, maintenance, supply classes, transport, medical and personnel services.',
  },
  { code: '17', name: 'Naval', doc: 'Naval elements operating as land units.' },
  { code: '18', name: 'Named headquarters', doc: 'Specific NATO and multinational headquarters.' },
  { code: '19', name: 'Emergency operation', doc: 'Emergency operation units.' },
  {
    code: '20',
    name: 'Law enforcement',
    doc: 'Police, border, customs and other law-enforcement bodies.',
  },
  { code: '21', name: 'Cyberspace', doc: 'Cyberspace units.' },
];

/** Land unit (symbol set 10) entities, keyed by the six-digit entity code. */
export const ENTITIES = [
  ['110000', 'Command and control'],
  ['110100', 'Broadcast transmitter antenna'],
  ['110200', 'Civil affairs'],
  ['110300', 'Civil-military cooperation'],
  ['110400', 'Information operations'],
  ['110500', 'Liaison'],
  ['110501', 'Liaison – reconnaissance', 'removed'],
  ['110600', 'Psychological operations (MISO)'],
  ['110601', 'Psychological operations – broadcast transmitter antenna'],
  ['110700', 'Radio'],
  ['110800', 'Radio relay'],
  ['110900', 'Radio teletype centre'],
  ['111000', 'Signal'],
  ['111001', 'Signal – radio'],
  ['111002', 'Signal – radio relay'],
  ['111003', 'Signal – teletype'],
  ['111004', 'Signal – tactical satellite', 'removed'],
  ['111005', 'Signal – video imagery (combat camera)'],
  ['111100', 'Tactical satellite', 'removed'],
  ['111200', 'Video imagery (combat camera)'],
  ['111300', 'Space'],
  ['111400', 'Special troops'],
  ['111500', 'Multi-domain'],
  ['120100', 'Air assault with organic lift'],
  ['120200', 'Air traffic services / airfield operations'],
  ['120300', 'Amphibious', 'removed'],
  ['120400', 'Anti-tank / anti-armour'],
  ['120401', 'Anti-tank – armoured'],
  ['120402', 'Anti-tank – motorized'],
  ['120500', 'Armour / armoured / mechanized / tracked'],
  ['120501', 'Armour – reconnaissance / cavalry'],
  ['120502', 'Armour – amphibious'],
  ['120600', 'Aviation – rotary wing'],
  ['120601', 'Aviation – rotary wing reconnaissance'],
  ['120700', 'Aviation – composite'],
  ['120800', 'Aviation – fixed wing'],
  ['120801', 'Aviation – fixed wing reconnaissance'],
  ['120900', 'Combat'],
  ['121000', 'Combined arms'],
  ['121100', 'Infantry'],
  ['121101', 'Infantry – amphibious'],
  ['121102', 'Infantry – armoured / mechanized / tracked'],
  ['121103', 'Infantry – main gun system'],
  ['121104', 'Infantry – motorized'],
  ['121105', 'Infantry – fighting vehicle'],
  ['121106', 'Main gun system'],
  ['121200', 'Observer'],
  ['121300', 'Reconnaissance / cavalry / scout'],
  ['121301', 'Reconnaissance – reconnaissance and surveillance'],
  ['121302', 'Reconnaissance – amphibious (marine)'],
  ['121303', 'Reconnaissance – motorized'],
  ['121400', 'Sea-air-land (SEAL)'],
  ['121500', 'Sniper'],
  ['121600', 'Surveillance'],
  ['121700', 'Special forces'],
  ['121800', 'Special operations forces (SOF)'],
  ['121801', 'SOF – fixed wing psychological operations'],
  ['121802', 'SOF – ground'],
  ['121803', 'SOF – special boat', 'removed'],
  ['121804', 'SOF – special submarine', 'removed'],
  ['121805', 'SOF – underwater demolition team'],
  ['121900', 'Unmanned systems'],
  ['122000', 'Ranger'],
  ['130100', 'Air defence'],
  ['130101', 'Air defence – main gun system'],
  ['130102', 'Air defence – missile'],
  ['130103', 'Air defence – air and missile defence'],
  ['130200', 'Air and naval gunfire liaison company'],
  ['130300', 'Field artillery'],
  ['130301', 'Field artillery – self-propelled', 'removed'],
  ['130302', 'Field artillery – self-propelled target acquisition', 'removed'],
  ['130303', 'Field artillery – target acquisition'],
  ['130400', 'Field artillery observer'],
  ['130500', 'Joint fire support'],
  ['130600', 'Meteorological'],
  ['130700', 'Missile'],
  ['130800', 'Mortar'],
  ['130801', 'Mortar – armoured / mechanized / tracked', 'removed'],
  ['130802', 'Mortar – self-propelled wheeled'],
  ['130803', 'Mortar – towed', 'removed'],
  ['130900', 'Survey'],
  ['140100', 'CBRN defence'],
  ['140101', 'CBRN – mechanized', 'removed'],
  ['140102', 'CBRN – motorized'],
  ['140103', 'CBRN – reconnaissance'],
  ['140104', 'CBRN – armoured reconnaissance', 'removed'],
  ['140105', 'CBRN – motorized reconnaissance'],
  ['140106', 'CBRNE (high-yield explosives)'],
  ['140200', 'Combat support (manoeuvre enhancement)'],
  ['140300', 'Criminal investigation division'],
  ['140400', 'Diving'],
  ['140500', 'Dog'],
  ['140600', 'Drilling'],
  ['140700', 'Engineer'],
  ['140701', 'Engineer – mechanized'],
  ['140702', 'Engineer – motorized'],
  ['140703', 'Engineer – reconnaissance'],
  ['140800', 'Explosive ordnance disposal (EOD)'],
  ['140900', 'Field camp construction'],
  ['141000', 'Fire fighting / fire protection'],
  ['141100', 'Geospatial support'],
  ['141200', 'Military police'],
  ['141300', 'Mine'],
  ['141400', 'Mine clearing'],
  ['141500', 'Mine launching'],
  ['141600', 'Mine laying'],
  ['141700', 'Security'],
  ['141701', 'Security – mechanized', 'removed'],
  ['141702', 'Security – motorized'],
  ['141800', 'Search and rescue'],
  ['141801', 'Personnel recovery (isolated personnel)'],
  ['141900', 'Security police (air)', 'removed'],
  ['142000', 'Shore patrol'],
  ['142100', 'Topographic'],
  ['142200', 'Air and missile defence'],
  ['150100', 'Analysis'],
  ['150200', 'Counter-intelligence'],
  ['150300', 'Direction finding'],
  ['150400', 'Electronic ranging'],
  ['150500', 'Electronic warfare'],
  ['150501', 'Electronic warfare – analysis'],
  ['150502', 'Electronic warfare – direction finding'],
  ['150503', 'Electronic warfare – intercept'],
  ['150504', 'Electronic warfare – jamming', 'removed'],
  ['150505', 'Electronic warfare – search', 'removed'],
  ['150600', 'Intercept (search and recording)'],
  ['150700', 'Interrogation'],
  ['150800', 'Jamming'],
  ['150900', 'Joint intelligence centre'],
  ['151000', 'Military intelligence'],
  ['151100', 'Search'],
  ['151200', 'Sensor'],
  ['151300', 'Military history'],
  ['160000', 'Sustainment'],
  ['160100', 'Administrative'],
  ['160200', 'All classes of supply'],
  ['160300', 'Airport of debarkation', 'removed'],
  ['160400', 'Ammunition'],
  ['160500', 'Band'],
  ['160501', 'Army music'],
  ['160600', 'Combat service support'],
  ['160700', 'Finance'],
  ['160800', 'Judge advocate general (legal)'],
  ['160900', 'Labour'],
  ['161000', 'Laundry / bath'],
  ['161100', 'Maintenance'],
  ['161200', 'Materiel'],
  ['161300', 'Medical'],
  ['161400', 'Medical treatment facility'],
  ['161500', 'Morale, welfare and recreation'],
  ['161600', 'Mortuary affairs'],
  ['161700', 'Multiple classes of supply'],
  ['161800', 'NATO supply class I'],
  ['161900', 'NATO supply class II', 'removed'],
  ['162000', 'NATO supply class III'],
  ['162100', 'NATO supply class IV'],
  ['162200', 'NATO supply class V', 'removed'],
  ['162300', 'Ordnance'],
  ['162400', 'Personnel services'],
  ['162500', 'Petroleum, oil and lubricants'],
  ['162600', 'Pipeline', 'removed'],
  ['162700', 'Postal', 'removed'],
  ['162800', 'Public affairs / public information'],
  ['162900', 'Quartermaster'],
  ['163000', 'Railhead', 'removed'],
  ['163100', 'Religious support'],
  ['163200', 'Replacement holding unit'],
  ['163300', 'Seaport of debarkation', 'removed'],
  ['163400', 'Supply', 'removed'],
  ['163500', 'Joint information bureau'],
  ['163600', 'Transportation'],
  ['163601', 'Transportation – floating craft', 'removed'],
  ['163700', 'US supply class I'],
  ['163800', 'US supply class II', 'removed'],
  ['163900', 'US supply class III', 'removed'],
  ['164000', 'US supply class IV'],
  ['164100', 'US supply class V', 'removed'],
  ['164200', 'US supply class VI'],
  ['164300', 'US supply class VII'],
  ['164400', 'US supply class VIII'],
  ['164500', 'US supply class IX'],
  ['164600', 'US supply class X'],
  ['164700', 'Water', 'removed'],
  ['164800', 'Water purification'],
  ['164900', 'Public affairs broadcast'],
  ['165000', 'NATO all classes of supply', 'removed'],
  ['165100', 'Interpreter / translator'],
  ['165200', 'Support'],
  ['165300', 'Army field support'],
  ['165400', 'Contracting services'],
  ['165500', 'Parachute rigger'],
  ['165600', 'Human resources'],
  ['170100', 'Naval'],
  ['180100', 'Allied Rapid Reaction Corps (ARRC)'],
  ['180200', 'Allied Command Operations'],
  ['180300', 'International Security Assistance Force (ISAF)'],
  ['180400', 'Multinational'],
  ['190000', 'Emergency operation'],
  ['200000', 'Law enforcement'],
  ['200100', 'Bureau of Alcohol, Tobacco, Firearms and Explosives (ATF)'],
  ['200200', 'Border patrol'],
  ['200300', 'Customs service'],
  ['200400', 'Drug Enforcement Administration (DEA)'],
  ['200500', 'Department of Justice (DOJ)'],
  ['200600', 'Federal Bureau of Investigation (FBI)'],
  ['200700', 'Police'],
  ['200800', 'Prison'],
  ['200900', 'US Secret Service'],
  ['201000', 'Transportation Security Administration (TSA)'],
  ['201100', 'Coast guard / law-enforcement vessel'],
  ['201200', 'US Marshals Service'],
  ['201300', 'Internal security force'],
  ['210000', 'Cyberspace'],
].map(([code, name, in2525E]) => ({
  code,
  name,
  group: code.slice(0, 2),
  ...editionNote(in2525E),
}));

/** Land unit sector 1 modifiers (upper part of the frame), APP-6 variants. */
export const MODIFIERS_1 = [
  ['00', 'None'],
  ['01', 'Airmobile / air assault'],
  ['02', 'Area'],
  ['03', 'Attack', 'common'],
  ['04', 'Biological'],
  ['05', 'Border'],
  ['06', 'Bridging', 'common'],
  ['07', 'Chemical', 'common'],
  ['08', 'Close protection', 'common'],
  ['09', 'Combat', 'common'],
  ['10', 'Command and control', 'common'],
  ['11', 'Communications contingency package'],
  ['12', 'Construction'],
  ['13', 'Cross-cultural communication'],
  ['14', 'Crowd and riot control', 'common'],
  ['15', 'Decontamination', 'common'],
  ['16', 'Detention'],
  ['17', 'Direct communications'],
  ['18', 'Diving'],
  ['19', 'Division'],
  ['20', 'Dog'],
  ['21', 'Drilling'],
  ['22', 'Electro-optical'],
  ['23', 'Enhanced'],
  ['24', 'Explosive ordnance disposal', 'common'],
  ['25', 'Fire direction centre'],
  ['26', 'Force'],
  ['27', 'Forward'],
  ['28', 'Ground station module'],
  ['29', 'Landing support'],
  ['30', 'Large extension node', 'removed'],
  ['31', 'Maintenance', 'common'],
  ['32', 'Meteorological'],
  ['33', 'Mine countermeasure', 'common'],
  ['34', 'Missile'],
  ['35', '(Mobile) advisor and support'],
  ['36', 'Mobile subscriber equipment'],
  ['37', 'Mobility support'],
  ['38', 'Movement control centre', 'removed'],
  ['39', 'Multinational'],
  ['40', 'Multinational specialized unit'],
  ['41', 'Multiple rocket launcher'],
  ['42', 'NATO medical role 1'],
  ['43', 'NATO medical role 2'],
  ['44', 'NATO medical role 3'],
  ['45', 'NATO medical role 4'],
  ['46', 'Naval'],
  ['47', 'Node centre', 'removed'],
  ['48', 'Nuclear', 'common'],
  ['49', 'Operations'],
  ['50', 'Radar'],
  ['51', 'RFID interrogator / sensor'],
  ['52', 'Radiological', 'common'],
  ['53', 'Search and rescue', 'common'],
  ['54', 'Security', 'common'],
  ['55', 'Sensor'],
  ['56', 'Sensor control module', 'removed'],
  ['57', 'Signals intelligence'],
  ['58', 'Single shelter switch', 'removed'],
  ['59', 'Single rocket launcher'],
  ['60', 'Smoke'],
  ['61', 'Sniper', 'common'],
  ['62', 'Sound ranging'],
  ['63', 'Special operations forces', 'common'],
  ['64', 'Special weapons and tactics', 'common'],
  ['65', 'Survey'],
  ['66', 'Tactical exploitation'],
  ['67', 'Target acquisition'],
  ['68', 'Topographic'],
  ['69', 'Utility', 'common'],
  ['70', 'Video imagery'],
  ['71', 'Accident'],
  ['72', 'Other'],
  ['73', 'Civilian'],
  ['74', 'Antisubmarine warfare'],
  ['75', 'Medevac', 'common'],
  ['76', 'Ranger', 'removed'],
  ['77', 'Support'],
  ['78', 'Aviation', 'removed'],
  ['79', 'Route, reconnaissance and clearance'],
  ['80', 'Tilt-rotor', 'common'],
  ['84', 'Assault'],
  ['85', 'Weapons', 'common'],
  ['86', 'Criminal investigation division'],
  ['87', 'Digital'],
  ['88', 'Network / network operations'],
  ['89', 'Airfield, aerial port of debarkation or embarkation'],
  ['90', 'Pipeline'],
  ['91', 'Postal'],
  ['92', 'Water', 'common'],
  ['93', 'Independent command', 'removed'],
  ['94', 'Theatre'],
  ['95', 'Army'],
  ['96', 'Corps'],
  ['97', 'Brigade', 'common'],
  ['98', 'Headquarters element'],
  ['99', 'Multi-domain'],
].map(([code, name, in2525E]) => ({ code, name, ...editionNote(in2525E) }));

/** Land unit sector 2 modifiers (lower part of the frame). */
export const MODIFIERS_2 = [
  ['00', 'None'],
  ['01', 'Airborne', 'common'],
  ['02', 'Arctic'],
  ['03', 'Battle damage repair'],
  ['04', 'Bicycle equipped', 'common'],
  ['05', 'Casualty staging'],
  ['06', 'Clearing'],
  ['07', 'Close range', 'common'],
  ['08', 'Control'],
  ['09', 'Decontamination'],
  ['10', 'Demolition'],
  ['11', 'Dental'],
  ['12', 'Digital'],
  ['13', 'Enhanced position location reporting system'],
  ['14', 'Equipment', 'removed'],
  ['15', 'Heavy', 'common'],
  ['16', 'High altitude'],
  ['17', 'Intermodal'],
  ['18', 'Intensive care'],
  ['19', 'Light', 'common'],
  ['20', 'Laboratory', 'common'],
  ['21', 'Launcher'],
  ['22', 'Long range', 'common'],
  ['23', 'Low altitude'],
  ['24', 'Medium', 'common'],
  ['25', 'Medium altitude'],
  ['26', 'Medium range', 'common'],
  ['27', 'Mountain', 'common'],
  ['28', 'High to medium altitude'],
  ['29', 'Multi-channel'],
  ['30', 'Optical (flash)'],
  ['31', 'Pack animal'],
  ['32', 'Patient evacuation coordination'],
  ['33', 'Preventive maintenance'],
  ['34', 'Psychological'],
  ['35', 'Radio relay line of sight'],
  ['36', 'Railroad', 'common'],
  ['37', 'Recovery (unmanned systems)'],
  ['38', 'Recovery (maintenance)'],
  ['39', 'Rescue coordination centre'],
  ['40', 'Riverine'],
  ['41', 'Single channel'],
  ['42', 'Ski', 'common'],
  ['43', 'Short range', 'common'],
  ['44', 'Strategic'],
  ['45', 'Support'],
  ['46', 'Tactical'],
  ['47', 'Towed'],
  ['48', 'Troop'],
  ['49', 'Vertical or short take-off and landing'],
  ['50', 'Veterinary'],
  ['51', 'Wheeled', 'common'],
  ['52', 'High to low altitude'],
  ['53', 'Medium to low altitude'],
  ['54', 'Attack'],
  ['55', 'Refuel'],
  ['56', 'Utility'],
  ['57', 'Combat search and rescue'],
  ['58', 'Guerrilla'],
  ['59', 'Air assault'],
  ['60', 'Amphibious'],
  ['61', 'Very heavy'],
  ['62', 'Supply', 'common'],
  ['63', 'Cyberspace', 'common'],
  ['64', 'Navy barge, self-propelled'],
  ['65', 'Navy barge, not self-propelled'],
  ['66', 'Launch'],
  ['67', 'Landing craft'],
  ['68', 'Landing ship'],
  ['69', 'Service craft / yard'],
  ['70', 'Tug, harbour'],
  ['71', 'Ocean-going tug'],
  ['72', 'Surface deployment and distribution command'],
  ['73', 'Non-combatant generic vessel'],
  ['74', 'Composite'],
  ['75', 'Shelter'],
  ['76', 'Light and medium', 'common'],
  ['77', 'Self-propelled', 'removed'],
  ['78', 'Security force assistance', 'common'],
  ['81', 'Surgical'],
  ['82', 'Blood'],
  ['83', 'Combat and operational stress control'],
  ['84', 'Jamming', 'common'],
  ['86', 'Optometry'],
  ['87', 'Preventive medicine'],
  ['89', 'Air defence'],
].map(([code, name, in2525E]) => ({ code, name, ...editionNote(in2525E) }));

/**
 * Land unit amplifiers, MIL-STD-2525E appendix E table E-II (descriptions
 * paraphrased). `option` is the milsymbol option that draws the field, where
 * one exists; `sample` fills the anatomy example.
 */
export const AMPLIFIERS = [
  {
    field: 'A',
    name: 'Symbol icon',
    doc: 'The innermost part of the symbol: the icon and its sector modifiers, from SIDC positions 11–20.',
  },
  {
    field: 'B',
    name: 'Echelon',
    doc: 'Graphic above the frame giving the command level (SIDC positions 9–10).',
  },
  {
    field: 'C',
    name: 'Quantity',
    doc: 'Number of items present; up to 19 characters.',
    option: 'quantity',
  },
  {
    field: 'D',
    name: 'Task force',
    doc: 'Bracket over the echelon marking a unit or activity as a task force (SIDC position 8).',
  },
  {
    field: 'F',
    name: 'Reinforced or reduced',
    doc: '(+) reinforced, (−) reduced, (±) reinforced and reduced.',
    option: 'reinforcedReduced',
    sample: '(+)',
  },
  {
    field: 'G',
    name: 'Staff comments',
    doc: 'Free text for units, equipment and installations; content is implementation-specific.',
    option: 'staffComments',
    sample: 'RESERVE',
  },
  {
    field: 'H',
    name: 'Additional information',
    doc: 'Free text for units, equipment and installations; content is implementation-specific.',
    option: 'additionalInformation',
    sample: 'CV90',
  },
  {
    field: 'J',
    name: 'Evaluation rating',
    doc: 'Confidence in the information: source reliability letter (A–F) and information credibility digit (1–6), e.g. B2.',
    option: 'evaluationRating',
    sample: 'B2',
  },
  {
    field: 'K',
    name: 'Combat effectiveness',
    doc: 'FO fully, SO substantially, MO marginally, NO not operational, UNK unknown.',
    option: 'combatEffectiveness',
    sample: 'SO',
  },
  {
    field: 'L',
    name: 'Signature equipment',
    doc: 'For hostile equipment: ! marks detectable electronic signatures.',
    option: 'signatureEquipment',
  },
  {
    field: 'M',
    name: 'Higher formation',
    doc: 'Number or title of the higher echelon command; corps in Roman numerals.',
    option: 'higherFormation',
    sample: '4',
  },
  {
    field: 'P',
    name: 'IFF/SIF',
    doc: 'Identification friend or foe modes and codes, e.g. 2:1234.',
    option: 'iffSif',
  },
  {
    field: 'Q',
    name: 'Direction of movement',
    doc: 'Arrow giving the direction of movement or intended movement.',
    option: 'direction',
  },
  {
    field: 'R',
    name: 'Mobility',
    doc: 'Graphic below equipment frames giving its mobility (SIDC positions 9–10).',
  },
  {
    field: 'S',
    name: 'Headquarters staff',
    doc: 'Staff down from the frame’s lower left marking a headquarters; its foot is the HQ’s location (SIDC position 8).',
  },
  {
    field: 'T',
    name: 'Unique designation',
    doc: 'Identifies this particular unit, or its track number.',
    option: 'uniqueDesignation',
    sample: '42',
  },
  {
    field: 'V',
    name: 'Type',
    doc: 'Type of equipment.',
    option: 'type',
  },
  {
    field: 'W',
    name: 'Date-time group',
    doc: 'DDHHMMSSZMONYYYY, or O/O for on order, e.g. 251200ZSEP2026.',
    option: 'dtg',
    sample: '251200ZSEP2026',
  },
  {
    field: 'X',
    name: 'Altitude / depth',
    doc: 'Altitude, flight level, depth or height, with its unit, e.g. 1500MSL.',
    option: 'altitudeDepth',
  },
  {
    field: 'Y',
    name: 'Location',
    doc: 'Position in degrees and decimal minutes, MGRS, GARS or another display format.',
    option: 'location',
  },
  {
    field: 'Z',
    name: 'Speed',
    doc: 'Velocity of units and equipment.',
    option: 'speed',
  },
  {
    field: 'AA',
    name: 'Special C2 headquarters',
    doc: 'A named command (SHAPE, CJTF, MJTF…), written inside the frame.',
    option: 'specialHeadquarters',
  },
  {
    field: 'AD',
    name: 'Platform type',
    doc: 'Electronic intelligence notation (ELNOT) or communications emitter notation (CENOT).',
    option: 'platformType',
  },
  {
    field: 'AE',
    name: 'Equipment teardown time',
    doc: 'Teardown time in minutes.',
    option: 'equipmentTeardownTime',
  },
  {
    field: 'AF',
    name: 'Common identifier',
    doc: 'Common name of the system, e.g. Hawk for the Hawk SAM system.',
    option: 'commonIdentifier',
  },
  {
    field: 'AL',
    name: 'Operational condition',
    doc: 'Coloured bar below the frame for equipment and installations (SIDC position 7).',
  },
  {
    field: 'AO',
    name: 'Engagement bar',
    doc: 'Bar atop the symbol: local/remote status, engagement status and weapon type.',
    option: 'engagementBar',
  },
  {
    field: 'AQ',
    name: 'Guarded unit',
    doc: 'In ballistic missile defence, the unit guarding this track.',
    option: 'guardedUnit',
  },
  {
    field: 'AS',
    name: 'Country',
    doc: 'Three-letter code of the country of origin.',
    option: 'country',
  },
];

/**
 * Where each amplifier sits around a land unit frame, MIL-STD-2525E figure
 * E-3: rows top to bottom, each `[left, centre, right]`; a cell lists the
 * fields sharing that place, null where nothing goes. The frame spans rows
 * 2–6 of the centre column; `A` and `AA` are inside it.
 */
export const AMPLIFIER_LAYOUT = [
  [null, ['AO'], null],
  [null, ['B', 'D'], null],
  [['W'], null, ['F', 'AS']],
  [['X', 'Y'], null, ['G', 'AQ']],
  [
    ['V', 'AD', 'AE'],
    ['A', 'AA'],
    ['H', 'AF'],
  ],
  [['C', 'T'], null, ['M']],
  [['Z'], null, ['J', 'K', 'L', 'P']],
  [null, ['R'], null],
  [null, ['AL'], null],
  [['S'], null, ['Q']],
];

/** The fields a custom ORBAT unit may set, in the order they are edited. */
export const UNIT_TEXT_FIELDS = [
  { key: 'designation', field: 'T', option: 'uniqueDesignation', label: 'Unique designation' },
  { key: 'higherFormation', field: 'M', option: 'higherFormation', label: 'Higher formation' },
  { key: 'reinforced', field: 'F', option: 'reinforcedReduced', label: 'Reinforced / reduced' },
  {
    key: 'additional',
    field: 'H',
    option: 'additionalInformation',
    label: 'Additional information',
  },
];

export const REINFORCED = [
  { code: '', name: 'Neither' },
  { code: '(+)', name: 'Reinforced (+)' },
  { code: '(-)', name: 'Reduced (−)' },
  { code: '(±)', name: 'Reinforced and reduced (±)' },
];

const byCode = (list) => new Map(list.map((item) => [item.code, item]));

export const lookup = {
  version: byCode(VERSIONS),
  context: byCode(CONTEXTS),
  identity: byCode(IDENTITIES),
  symbolSet: byCode(SYMBOL_SETS),
  status: byCode(STATUSES),
  hqtfd: byCode(HQTFD),
  echelon: byCode(ECHELONS),
  entity: byCode(ENTITIES),
  group: byCode(ENTITY_GROUPS),
  modifier1: byCode(MODIFIERS_1),
  modifier2: byCode(MODIFIERS_2),
};
