// The exercise module's store: one SQLite file (exercise.db) behind the
// functions routes.js calls. Each area lives in its own file under store/;
// they share the connection through store/connection.js.
import { connect, database, disconnect } from './store/connection.ts';
import {
  addTrackPosition,
  createTrack,
  deleteTrack,
  listTracks,
  shapeTrack,
  updateTrack,
} from './store/tracks.ts';
import {
  cancelScenarioEvent,
  createScenarioEvent,
  dueScenarioEventIds,
  fireScenarioEvent,
  listMessages,
  listScenarioEvents,
  patchClock,
  readClock,
  shapeMessage,
  shapeScenarioEvent,
  updateScenarioEvent,
} from './store/scenarioEvents.ts';
import {
  createCollector,
  createTasking,
  deleteCollector,
  deleteTasking,
  listCollectionConflicts,
  listCollectors,
  listTaskings,
  shapeCollector,
  shapeTasking,
  updateCollector,
  updateTasking,
} from './store/collection.ts';
import {
  createCountry,
  createExampleScenario,
  createPlace,
  createScenario,
  deleteCountry,
  deletePlace,
  deleteScenario,
  duplicateScenario,
  getActiveScenario,
  getRegions,
  getScenario,
  listScenarios,
  updateCountry,
  updatePlace,
  updateScenario,
} from './store/scenarios.ts';
import {
  createEvidenceLink,
  createIndicator,
  createRequirement,
  createSir,
  deleteEvidenceLink,
  deleteIndicator,
  deleteRequirement,
  deleteSir,
  listRequirements,
  shapeRequirement,
  updateIndicator,
  updateRequirement,
  updateSir,
} from './store/requirements.ts';
import {
  createIntsum,
  deleteIntsum,
  draftIntsum,
  listIntsums,
  shapeIntsum,
  updateIntsum,
} from './store/intsum.ts';
import {
  createReport,
  deleteReport,
  listReports,
  shapeReport,
  updateReport,
} from './store/reports.ts';
import { createRfi, deleteRfi, listRfis, shapeRfi, transitionRfi, updateRfi } from './store/rfi.ts';
import {
  createSituation,
  deleteSituation,
  getInstructorData,
  listSituations,
  patchStory,
  readStory,
  updateSituation,
} from './store/instructor.ts';
import { importIpbStudy, listNais, shapeNai } from './store/ipbStudy.ts';
import { listActivity } from './store/activity.ts';
import { touchRequirementsForReport } from './store/shared.ts';

export function openStore(file: string, { regionsFile }: { regionsFile?: string } = {}) {
  connect(file, { regionsFile });
  return {
    database,
    listRequirements,
    createRequirement,
    updateRequirement,
    deleteRequirement,
    createSir,
    updateSir,
    deleteSir,
    createIndicator,
    updateIndicator,
    deleteIndicator,
    createEvidenceLink,
    deleteEvidenceLink,
    importIpbStudy,
    listNais,
    listReports,
    createReport,
    updateReport,
    deleteReport,
    touchRequirementsForReport,
    listTracks,
    createTrack,
    updateTrack,
    deleteTrack,
    addTrackPosition,
    listCollectors,
    createCollector,
    updateCollector,
    deleteCollector,
    listTaskings,
    createTasking,
    updateTasking,
    deleteTasking,
    listCollectionConflicts,
    listIntsums,
    createIntsum,
    updateIntsum,
    deleteIntsum,
    draftIntsum,
    listRfis,
    createRfi,
    updateRfi,
    transitionRfi,
    deleteRfi,
    listMessages,
    readClock,
    patchClock,
    listScenarioEvents,
    createScenarioEvent,
    updateScenarioEvent,
    cancelScenarioEvent,
    fireScenarioEvent,
    dueScenarioEventIds,
    getInstructorData,
    readStory,
    patchStory,
    listSituations,
    createSituation,
    updateSituation,
    deleteSituation,
    getRegions,
    listScenarios,
    createScenario,
    createExampleScenario,
    getScenario,
    updateScenario,
    deleteScenario,
    duplicateScenario,
    getActiveScenario,
    createCountry,
    updateCountry,
    deleteCountry,
    createPlace,
    updatePlace,
    deletePlace,
    listActivity,
    shapeRequirement,
    shapeReport,
    shapeTrack,
    shapeCollector,
    shapeTasking,
    shapeIntsum,
    shapeRfi,
    shapeNai,
    shapeMessage,
    shapeScenarioEvent,
    close,
  };
}

function close() {
  disconnect();
}
